name: ðŸ˜ Gradle Profiler

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  actions: read
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  PROFILER_VERSION: "0.23.0" # https://github.com/gradle/gradle-profiler/releases

jobs:

  gradle-profiler:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v6
        with:
          lfs: true
      - uses: ./.github/actions/setup-java
      - uses: ./.github/actions/setup-gradle
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - uses: ./.github/actions/setup-gradle-properties

      - name: Cache Gradle Profiler
        id: cache-gradle-profiler
        uses: actions/cache@v5
        with:
          path: ~/gradle-profiler
          key: gradle-profiler-${{ env.PROFILER_VERSION }}

      - name: Install Gradle Profiler
        if: steps.cache-gradle-profiler.outputs.cache-hit != 'true'
        run: |
          wget -q "https://repo1.maven.org/maven2/org/gradle/profiler/gradle-profiler/${PROFILER_VERSION}/gradle-profiler-${PROFILER_VERSION}.zip"
          unzip -q "gradle-profiler-${PROFILER_VERSION}.zip" -d "$HOME/gradle-profiler"

      - name: Add Gradle Profiler to path
        run: echo "$HOME/gradle-profiler/gradle-profiler-${PROFILER_VERSION}/bin" >> "$GITHUB_PATH"

      - name: Run benchmark
        run: >-
          gradle-profiler
          --benchmark --project-dir .
          --scenario-file .gradle-profiler/validate.scenarios
          --measure-gc --measure-local-build-cache

      - name: Archive reports
        uses: actions/upload-artifact@v6
        with:
          name: gradle-profiler-reports
          path: profile-out
          if-no-files-found: error
